[project]
name = "facedet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11"
dependencies = [
    "dlib>=20.0.0",
    "insightface>=0.7.3",
    "numpy==1.23.5",
    "onnxruntime>=1.24.2",
    "opencv-contrib-python>=4.8.1.78",
    "opencv-python==4.8.1.78",
]
